spring:
  application:
    name: knowledge-mining
  jersey:
    application-path: /knowledge-miming/api
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/knowledge_mining
server:
  port: 19989

jersey:
  swagger:
    ip: 192.168.1.72
    port: ${server.port}