spring:
  application:
    name: knowledge-mining
  jersey:
    application-path: /knowledge-miming/api
  data:
    mongodb:
      uri: mongodb://192.168.1.156:27017/knowledge_mining
server:
  port: 19989

jersey:
  swagger:
    ip: 127.0.0.1
    port: ${server.port}